export const INCREMENT = 'INCREMENT';

export const DECREMENT = 'DECREMENT';
export const FETCH_USER_REQUEST = 'FETCH_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_USER_ERR = 'FETCH_ERR';
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERR = 'CREATE_USER_ERR';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';